const API=window.APP_CONFIG.API_URL;let data={positions:[],products:[],stock:[],orders:[],orderItems:[],wishRequests:[],analytics:{}};let uploaded=[];
async function api(action,payload={},method='GET'){if(!API||API.includes('PASTE_'))throw new Error('API URL is not configured');if(method==='GET')return fetch(`${API}?action=${action}`).then(r=>r.json());return fetch(API,{method:'POST',body:JSON.stringify({action,...payload})}).then(r=>r.json())}
function toast(m){const e=document.getElementById('toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function money(v){return `${Number(v||0).toFixed(0)}₾`}
async function load(){try{const r=await api('adminData');if(!r.ok)throw new Error(r.error);data=r;render()}catch(e){toast(e.message)}}
function render(){document.getElementById('adminPosition').innerHTML='<option value="">აირჩიე პოზიცია</option>'+data.positions.filter(p=>p.Status==='active').map(p=>`<option value="${p.PositionID}">${p.NameKA}</option>`).join('');renderProducts();renderOrders();renderWish();renderAnalytics()}
function renderProducts(){document.getElementById('productsTable').innerHTML=table(['კოდი','პოზიცია','სახელი','ფასი','ზომები'],data.products.map(p=>{const pos=data.positions.find(x=>x.PositionID===p.PositionID)||{};const sizes=data.stock.filter(s=>s.ProductID===p.ProductID).map(s=>`${s.Size}: ${s.Qty}`).join(', ');return [p.Code,pos.NameKA||'',p.NameKA,money(p.Price),sizes]}))}
function renderOrders(){document.getElementById('ordersTable').innerHTML=table(['თარიღი','კლიენტი','ტელეფონი','ოთახი','დრო','ჯამი','სტატუსი'],data.orders.map(o=>[o.Date,o.CustomerName,o.Phone,o.RoomNumber,o.DeliveryTime,money(o.Total),statusSelect('orders',o.OrderID,o.Status)]))}
function renderWish(){document.getElementById('wishTable').innerHTML=table(['თარიღი','კლიენტი','ტელეფონი','ოთახი','შეტყობინება','სტატუსი'],data.wishRequests.map(w=>[w.Date,w.CustomerName,w.Phone,w.RoomNumber,w.Message,statusSelect('wish',w.RequestID,w.Status)]))}
function renderAnalytics(){const a=data.analytics||{};document.getElementById('analyticsBox').innerHTML=`<div class="metric-grid"><div class="metric"><span>პროდუქტები</span><br><b>${data.products.length}</b></div><div class="metric"><span>შეკვეთები</span><br><b>${data.orders.length}</b></div><div class="metric"><span>სურვილები</span><br><b>${data.wishRequests.length}</b></div><div class="metric"><span>დაბალი ნაშთი</span><br><b>${(a.lowStock||[]).length}</b></div></div><h3>ყველაზე გაყიდვადი</h3>${table(['კოდი','სახელი','გაყიდულია'],(a.bestSellers||[]).map(x=>[x.code,x.name,x.sold]))}<h3>დაბალი ნაშთი</h3>${table(['კოდი','ზომა','ხელმისაწვდომი'],(a.lowStock||[]).map(x=>[x.code,x.size,x.available]))}`}
function table(headers,rows){return `<table class="table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c??''}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function statusSelect(type,id,status){return `<select onchange="changeStatus('${type}','${id}',this.value)"><option ${status==='new'?'selected':''} value="new">ახალი</option><option ${status==='confirmed'?'selected':''} value="confirmed">დადასტურებული</option><option ${status==='delivered'?'selected':''} value="delivered">მიტანილია</option><option ${status==='done'?'selected':''} value="done">დასრულებული</option><option ${status==='cancelled'?'selected':''} value="cancelled">გაუქმებული</option></select>`}
async function changeStatus(type,id,status){const action=type==='wish'?'updateWishStatus':'updateOrderStatus';const r=await api(action,{id,status},'POST');if(!r.ok)return toast(r.error);toast('სტატუსი შეიცვალა');load()}
function addSize(){const d=document.createElement('div');d.className='split size-input';d.innerHTML='<input placeholder="ზომა" required><input type="number" placeholder="რაოდენობა" required>';document.getElementById('sizesBox').appendChild(d)}
async function uploadFiles(files){uploaded=[];document.getElementById('photoPreview').innerHTML='იტვირთება...';for(const f of files){const base64=await fileToBase64(f);const r=await api('uploadImage',{fileName:f.name,mimeType:f.type,base64},'POST');if(!r.ok)throw new Error(r.error);uploaded.push(r.url)}document.getElementById('photoPreview').innerHTML=uploaded.map((u,i)=>`<span class="chip">ფოტო ${i+1}${i===0?' მთავარი':''}</span>`).join('')}
function fileToBase64(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result).split(',')[1]);r.onerror=rej;r.readAsDataURL(file)})}
document.getElementById('positionForm').onsubmit=async e=>{e.preventDefault();const position=Object.fromEntries(new FormData(e.target).entries());const r=await api('savePosition',{position},'POST');if(!r.ok)return toast(r.error);e.target.reset();toast('პოზიცია დაემატა');load()};
document.getElementById('photoInput').onchange=e=>uploadFiles(e.target.files).catch(err=>toast(err.message));
document.getElementById('addSizeBtn').onclick=addSize;addSize();
document.getElementById('productForm').onsubmit=async e=>{e.preventDefault();const fd=Object.fromEntries(new FormData(e.target).entries());const sizes=[...document.querySelectorAll('.size-input')].map(d=>({size:d.children[0].value,qty:d.children[1].value})).filter(x=>x.size&&x.qty);const r=await api('saveProduct',{product:{...fd,images:uploaded,sizes}},'POST');if(!r.ok)return toast(r.error);e.target.reset();uploaded=[];document.getElementById('photoPreview').innerHTML='';document.getElementById('sizesBox').innerHTML='';addSize();toast('პროდუქტი შეინახა');load()};
document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.tab').forEach(t=>t.hidden=true);document.getElementById(b.dataset.tab).hidden=false});
load();
