const API=window.APP_CONFIG.API_URL;let data={products:[],stock:[],analytics:{}};let sale=[];
async function api(action,payload={},method='GET'){if(!API||API.includes('PASTE_'))throw new Error('API URL is not configured');if(method==='GET')return fetch(`${API}?action=${action}`).then(r=>r.json());return fetch(API,{method:'POST',body:JSON.stringify({action,...payload})}).then(r=>r.json())}
function toast(m){const e=document.getElementById('toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function money(v){return `${Number(v||0).toFixed(0)}₾`}
async function load(){try{const r=await api('adminData');if(!r.ok)throw new Error(r.error);data=r;renderProducts();renderSale();renderAnalytics()}catch(e){toast(e.message)}}
function renderProducts(){document.getElementById('productSelect').innerHTML='<option value="">აირჩიე პროდუქტი</option>'+data.products.filter(p=>p.Status==='active').map(p=>`<option value="${p.Code}">${p.Code} — ${p.NameKA}</option>`).join('')}
function selectedProduct(){const code=document.getElementById('codeInput').value.trim()||document.getElementById('productSelect').value;return data.products.find(p=>String(p.Code)===String(code))}
function renderSizes(){const p=selectedProduct();const sel=document.getElementById('sizeSelect');if(!p){sel.innerHTML='<option value="">ზომა</option>';return}const sizes=data.stock.filter(s=>s.ProductID===p.ProductID).map(s=>{const available=Number(s.Qty||0)-Number(s.ReservedQty||0);return `<option value="${s.Size}" ${available<=0?'disabled':''}>${s.Size} — ${available} ც.</option>`}).join('');sel.innerHTML='<option value="">ზომა</option>'+sizes}
function addItem(){const p=selectedProduct();if(!p)return toast('პროდუქტი ვერ მოიძებნა');const size=document.getElementById('sizeSelect').value;if(!size)return toast('აირჩიე ზომა');const qty=Number(document.getElementById('qtyInput').value||1);const discount=Number(document.getElementById('discountInput').value||0);const price=Number(p.Price||0);const finalPrice=Math.max(price-discount,0);sale.push({productId:p.ProductID,code:p.Code,nameKA:p.NameKA,size,qty,price,discount,finalPrice});renderSale()}
function renderSale(){const box=document.getElementById('saleItems');if(!sale.length){box.className='cart-items empty';box.textContent='ჯერ არაფერი დამატებულა';document.getElementById('saleTotal').textContent='0₾';return}box.className='cart-items';box.innerHTML=sale.map((i,ix)=>`<div class="cart-line"><div><b>${i.nameKA}</b><br><small>${i.code} / ${i.size} / ${i.qty} ც. / ფასდაკლება ${money(i.discount)}</small></div><div><b>${money(i.finalPrice*i.qty)}</b><br><button class="secondary" onclick="removeItem(${ix})">წაშლა</button></div></div>`).join('');document.getElementById('saleTotal').textContent=money(total())}
function removeItem(ix){sale.splice(ix,1);renderSale()}function total(){return sale.reduce((s,i)=>s+i.finalPrice*i.qty,0)}
async function completeSale(){if(!sale.length)return toast('გატარება ცარიელია');const cash=Number(document.getElementById('cashAmount').value||0);const card=Number(document.getElementById('cardAmount').value||0);if(cash+card!==total())return toast('ქეში + ტერმინალი უნდა უდრიდეს ჯამს');const r=await api('createSale',{sale:{cashier:document.getElementById('cashierName').value,cashAmount:cash,cardAmount:card,items:sale}},'POST');if(!r.ok)return toast(r.error);sale=[];document.getElementById('cashAmount').value='';document.getElementById('cardAmount').value='';toast('გაყიდვა დასრულდა');await load()}
async function closeDay(){const r=await api('closeDay',{close:{cashier:document.getElementById('cashierName').value}},'POST');if(!r.ok)return toast(r.error);toast(`დღე დაიხურა: ${money(r.total)} | ქეში ${money(r.cash)} | ტერმინალი ${money(r.card)}`)}
function renderAnalytics(){const a=data.analytics||{};document.getElementById('cashierAnalytics').innerHTML=`<h3>დაბალი ნაშთი</h3>${table(['კოდი','ზომა','ხელმისაწვდომი'],(a.lowStock||[]).map(x=>[x.code,x.size,x.available]))}<h3>ყველაზე გაყიდვადი</h3>${table(['კოდი','სახელი','გაყიდულია'],(a.bestSellers||[]).map(x=>[x.code,x.name,x.sold]))}`}
function table(headers,rows){return `<table class="table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c??''}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
document.getElementById('codeInput').addEventListener('input',renderSizes);document.getElementById('productSelect').addEventListener('change',()=>{document.getElementById('codeInput').value=document.getElementById('productSelect').value;renderSizes()});document.getElementById('addSaleItem').onclick=addItem;document.getElementById('completeSale').onclick=completeSale;document.getElementById('closeDay').onclick=closeDay;load();
